### ISSUE TITLE
Write QEP and port "click-click" editing to C++

### ISSUE THREAD

**Issue by vpicavet** [qwat/QWAT#121]
Following #78 when we have a working Python implementation, write a QEP and port it to QGIS core

**Comment by vpicavet** [comment]
See : qgis/QGIS-Enhancement-Proposals/issues/69

**Comment by haubourg** [comment]
@wonder-sk Hi Martin, I hope you're doing well. Can you tell us if things are moving for the new clic clic tool? 
We have a question from Lausanne too:
@dsavary asked if it was possible, and if feasable, to extend the prototype plugin to a fully functional one so that they use it during 2.18 LTR lifetime. From what I understood, it required the new snapping classes to work correctly; and they only landed in 3.0. Do you confirm?

**Comment by wonder-sk** [comment]
Hi @haubourg 

So we have PR https://github.com/qgis/QGIS/pull/4187 in fairly good shape. From the look of it, the are still few features missing compared to the existing node tool:
- integration with node editor
- better support for circular geometries (mainly display of curved rubber bands)
- validation of geometries (show warnings if editing operation ended up with invalid geometry - e.g. self-intersecting polygon ring)
- support for moving of multiple vertices at once (i.e. select vertices by rect + move them afterwards)
- better topological editing support (add common vertices to other features when vertices are moved/added)

If we get those bits done, it should be safe to fully replace the existing node tool - without that I am afraid some users may complain about lost functionality...

FYI I have used 33 hours so far on the C++ port.

For @dsavary 's comment - right now the Python plugin and C++ port are nearly 1:1 in terms of functionality - the c++ port has maybe two extra bugfixes. The python plugin uses snapping classes introduced already in 2.8 - so the plugin work fine in 2.18.

**Comment by 3nids** [comment]
@wonder-sk finance is the limiting point at the moment?

**Comment by wonder-sk** [comment]
@3nids maybe - I don't know - I just wanted to make sure that there is budget for the extra bits... I believe my original estimate for c++ port was 4 days. If it is fine to dedicate few extra days to the port, I should be able to get it finished by the end of the next week...

**Comment by haubourg** [comment]
@wonder-sk Hi Martin, thanks for the update. 
I had planned 5 days for you, and extending some days might not be a problem. Please just tell me if needed so that I keep track of the finances. This tool is really needed, and as you say, must be finished 100% so that users don't complain. 

We also had the "visual feedback for snapping" feature with 10 days ready for discussion. Let's finish this task first :-)

**Comment by wonder-sk** [comment]
OK great. I think with ~3 extra days of work we should hopefully have node tool ready for merging. A bit more if the extra functionality needs to be backported to the python plugin for 2.x.

Visual feedback for snapping is high on my to-do list, but yes let's get this bit finished first :-)

**Comment by wonder-sk** [comment]
https://github.com/qgis/QGIS/pull/4187 should be now feature complete and will be merged soon after notes from reviews are resolved.

**Comment by haubourg** [comment]
@wonder-sk Martin, Thanks for the update. 
We discussed the topic this morning in PSC.  As 2.18 will become a LTR and 3.2 is still a bit far away, @dsavary and @ponceta are willing to use the node tool plugin in production. What is still missing is the ability to open the qgsnodeeditor panel when activating this tool. 
I could'nt find a sip binding exposed in python. So my questions:
- is it possible in next 2.18 revision to wire the opening of the node editor panel ? 
- Could you estimate how much time you would need if it's doable ? 

Checking priorities, it appears to be more urgent than the visual snapping feedback task  .. 

Thanks for your lights!

**Comment by wonder-sk** [comment]
> is it possible in next 2.18 revision to wire the opening of the node editor panel ?

Unfortunately node editor is not available in QGIS API... We would need to basically take the node editor panel and reimplement it in the Python plugin. However, I am wondering if it would not be enough to just use the advanced digitizing dock widget - that one can be used to fix coordinates of node without dedicated node editor table...

> Could you estimate how much time you would need if it's doable ?

If we decide to reimplement node editor within the python plugin, it can be maybe 3-4 days of work...

Also, in the C++ port I have been adding further features (e.g. curved geometries, moving multiple nodes at once) and fixes - not sure if the Python node tool is good enough already for the clients or they will need 1:1 functionality...

**Comment by haubourg** [comment]
> Unfortunately node editor is not available in QGIS API... We would need to basically take the node editor panel and reimplement it in the Python plugin. 

Ok thanks for that.

> However, I am wondering if it would not be enough to just use the advanced digitizing dock widget - that one can be used to fix coordinates of node without dedicated node editor table..

Not sure I get your point. From what I get, this panel is only for new feature creation in 2.18 and only allows to precisely put XY drawing based on distance or angles. What Lausanne asks is to be able to set the Z value. 

>If we decide to reimplement node editor within the python plugin, it can be maybe 3-4 days of work...
 @dsavary here is the estimate then :)

**Comment by wonder-sk** [comment]
> Not sure I get your point. From what I get, this panel is only for new feature creation in 2.18 and only allows to precisely put XY drawing based on distance or angles. What Lausanne asks is to be able to set the Z value.

Oh I see - I thought the requirement was to set X/Y coordinates only... For Z values we would indeed need the node editor table.

**Comment by dsavary** [comment]
I tested the new "node tool" on qgis 2.99 (window) . very efficient to snap . good job.
I found 2 problems : 

- It don't take the Z defaut value of the project when you extend a 3d line .
- You can't open the "node/vertex editor panel" from the point layer when there is a point snap to a line and the two layers are in "edit mode". It open only the "node/vertex editor panel" from the line layer.

To better understand, see the demo : 
[node panel](https://share.oslandia.net/public/a070d4)
[extend line](https://share.oslandia.net/public/bab7e8)

**Comment by wonder-sk** [comment]
@dsavary The issues should be fixed now in qgis master

**Comment by dsavary** [comment]
@wonder-sk thanks ! the first point (extend line) is ok. But, for the second point, it doesn't work if the points are on the ends of a line, It works well on intermediate vertex of a line. 
The problem is still present if the points are on the edge of a polygon (layers must be in edit mode).

**Comment by haubourg** [comment]
I think it's done!
