### ISSUE TITLE
Advanced digitizing panel : the "rubberband"  disappear after a zoom extent 

### ISSUE THREAD

**Issue by dsavary** [qwat/QWAT#196]
We work on QGIS 2.18 to train ours users with the CAD tool and advanced digitizing panel. 
When we begin to draw some feature with the advanced digitizing panel on a little area (scale : 1:500), everything is working well. 
But, when we do a zoom extent and zoom in on  another area, the "rubber band" from the advanced digitizing panel disappear . We don't see the "green line" for the angle and the "blue circle" for the distance any more. 
Have you already seen this bug ? 
I will show you a demo example to better understand the problem.

**Comment by 3nids** [comment]
fixed in [master](https://github.com/qgis/QGIS/commit/40e5ddad30dc2cdf55b1615df906149520227f98)

struggling a bit for 2.18

**Comment by dsavary** [comment]
@3nids  impossible to fix this for the version 2.18 LTR in septembre :)  ?

**Comment by 3nids** [comment]
I gave it a try but don't understand the issue, weird.

**Comment by lbartoletti** [comment]
@3nids seems still present in QGIS 3.4.1 I can reproduce it "sometimes"/"randomly"...
